In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lst = [1,2,3,4]
arr1 = np.array(lst)
arr1

array([1, 2, 3, 4])

In [5]:
data2 = [lst, [x+1 for x in lst]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.logspace(0,3,5) #equivalent to np.linspace(10^0, 10^3, 5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [17]:
arr = np.arange(5)
#arr.astype(float)
arr

array([0, 1, 2, 3, 4])

In [18]:
print(arr.dtype)
arr2.ndim

int32


2

In [22]:
arr2.shape
arr2.size
len(arr2)

2

In [26]:
a = np.arange(10, dtype = float)
a.reshape((2,5))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [29]:
b = np.array([1,2])
b[:, None]

array([[1],
       [2]])

In [30]:
arr[1:3]

array([1, 2])

In [33]:
arr.reshape((1,5)).T

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [34]:
#slicing returns a view of the original array

In [35]:
matrix = np.arange(10).reshape((2,5))
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
mat1 = matrix[0,:]
mat1[0] = 10
print(mat1)
matrix

[10  1  2  3  4]


array([[10,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [38]:
mat2 = matrix[0, [0,1,2,3,4]]
mat2[0] = 11
print(mat2)
matrix

[11  1  2  3  4]


array([[10,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [42]:
mat = np.array([[0,0,0],
                [10,10,10],
                [20,20,20],
                [30,30,30]])
mat.sum(axis=0)

array([60, 60, 60])